### PR TITLE
Remove unused storage items

### PR DESCRIPTION
**Pull request by Dinonard**
**Pull Request Summary**

Removes unused storage items from `pallet-dapps-staking`.
We don't need to bring these to Astar chain.

Migration code was kept for future reference.
We can remove it later if needed.

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tests and/or benchmarks are included
- [ ] changed API client type definition or chain metadata

### CODE REVIEW

**Review by Maar-io — APPROVED** [review]
LGTM

**Comment by codespool** [comment]
Looks good.
Can you just explain what's the reason to comment out all the unusable code instead of deleting it?

**Review by codespool — APPROVED** [review]

**Comment by Dinonard** [comment]
> Looks good. Can you just explain what's the reason to comment out all the unusable code instead of deleting it?

Please see PR summary.

**Comment by codespool** [comment]
> Please see PR summary.
🤦 oh, right, my bad, sorry

**Comment by Dinonard** [comment]
> > Please see PR summary.
> > facepalm oh, right, my bad, sorry

It's fine! xD

Fortunately, I've tagged PRs with storage migration so we can easily find them.
Let's get rid of migration code in some future PR just so we keep the size of current one as small as possible.

**Pull request merged**
