### PR TITLE
test: add test to `StakerInfo`

### PR DESCRIPTION
**Pull request by TarekkMA**
Add tests for `StakerInfo`.

polkadot: `12xH9F4aSGEq27AZxLqG15fheDTtSxh1rJkVSXQ2g59djs7u`

### CODE REVIEW

**Comment by Dinonard** [comment]
@TarekkMA hello, can you please explain what is the added value of these tests?

It's already covered in test module.

**Comment by TarekkMA** [comment]
@Dinonard 

These are unit tests focused on `StakerInfo` itself without other dependencies. It's like the documentation you have above each method (`stake`, `unstake`, `claim`) but it's actually validatable.

In Subsocial we were interested in creating something similar to dapps-staking, and I added these tests on our pallet. and I thought submitting them also here is a good idea since I used this same struct on our pallet.

**Comment by Dinonard** [comment]
Sure, I agree unit tests are very important.

What I meant is that the `StakerInfo` is already fully tested [here](https://github.com/AstarNetwork/astar-frame/blob/polkadot-v0.9.19/frame/dapps-staking/src/tests_lib.rs).

**Comment by TarekkMA** [comment]
Oh my bad, I didn't see these tests at all.

**Comment by TarekkMA** [comment]
Anyways thank you for your work on dapps-staking was very helpful.

Since this part of the code is already tested, you can close this PR.

**Comment by Dinonard** [comment]
Thank you for the effort though!

**Pull request closed without merging**
