### PR TITLE
rename plasm and fix links

### PR DESCRIPTION
**Pull request by Maar-io**
**Pull Request Summary**

Rename plasm to Astar and fix links

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [x] documentation changes
- [ ] tests and/or benchmarks are included
- [ ] changed API client type definition or chain metadata

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

**Fixes**
- (ex: Fix validation function)

**Changes**
- (ex: Change document B)

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Review by Dinonard — APPROVED** [review]

**Review by hoonsubin — APPROVED** [review]
LGTM

**Comment by hoonsubin** [comment]
When can we merge this?

**Comment by akru** [comment]
@Maar-io could you rebase it?

**Comment by akru** [comment]
Probably it's outdated, let me close it

**Pull request closed without merging**
